# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaciones',
            name='hora',
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='cantidad_personas',
            field=models.CharField(max_length=20),
        ),
    ]
