# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0002_auto_20170125_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='dia',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
