# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0003_reservaciones_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='restaurante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistemareservas.Restaurantes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='dia',
            field=models.DateField(max_length=20),
        ),
    ]
