# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0005_auto_20170126_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaciones',
            name='restaurante',
        ),
    ]
