# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0006_remove_reservaciones_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='restaurante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistemareservas.Restaurantes'),
            preserve_default=False,
        ),
    ]
