# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0007_reservaciones_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemareservas.Restaurantes'),
        ),
    ]
