# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0012_auto_20170126_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='dia',
            field=models.DateField(),
        ),
    ]
