# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0013_auto_20170126_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='hora',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
