# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0014_reservaciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='restaurantes',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
