# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemareservas', '0015_auto_20170126_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
