# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='dia',
            field=models.DateField(default=datetime.datetime(2017, 1, 27, 21, 44, 5, 354881, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='restaurantes',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='cantidad_personas',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='hora',
            field=models.CharField(max_length=20),
        ),
    ]
