# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_reservas', '0002_auto_20170127_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='dia',
            field=models.DateField(default=datetime.date(2017, 1, 27)),
        ),
    ]
