# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_reservas', '0005_auto_20170127_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='dia',
            field=models.DateField(default=datetime.datetime(2017, 1, 28, 15, 49, 47, 7875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='hora',
            field=models.CharField(default='00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='restaurantes',
            field=models.CharField(max_length=20),
        ),
    ]
